version: '3.8'

services:
  food-facts-api:
    build: .
    container_name: foodscholar
    ports:
      - "8080:8080"
    environment:
      - GROQ_API_KEY=_your_api_key_here_
      - PORT=8080
    volumes:
      - ./app.py:/app/app.py
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - food-facts-network

networks:
  food-facts-network:
    driver: bridge